/*
 * This Java source file was generated by the Gradle 'init' task.
 * Augustus DeGrandis
 * Lab6 
 * 5/28/2024
 */
package lab6;

public class Components {
    public static void main(String[] args) {
        System.out.println("Hello World");
    }
}
