/*
 * This Java source file was generated by the Gradle 'init' task.
 * Augustus Degrandis
 * 5/28/2024
 */
package lab6;

import org.junit.Test;
import static org.junit.Assert.*;

public class ComponentsTest {
    @Test public void test01() {
        App classUnderTest = new App();
        //Create Tests here if I want
    }
}
